#!/usr/bin/env bash
# Regenerates cloud-init.yaml from the files in this directory, so the unit,
# deploy script and configs live in exactly one place. CI should run this and
# fail on drift:  deploy/hetzner/build-cloud-init.sh && git diff --exit-code deploy/hetzner/cloud-init.yaml
set -euo pipefail
cd "$(dirname "$0")"

indent() { sed 's/^/      /' "$1"; }
file_entry() { # path mode [owner] [defer]
  printf '  - path: %s\n    permissions: "%s"\n' "$1" "$2"
  [[ -n "${3:-}" ]] && printf '    owner: %s\n' "$3"
  [[ -n "${4:-}" ]] && printf '    defer: true\n'
  printf '    content: |\n'
}

{
cat <<'EOF'
#cloud-config
# Hetzner Cloud user data for the flight-tracker VM (Ubuntu 24.04, CX23).
# GENERATED by deploy/hetzner/build-cloud-init.sh from the files next to it;
# edit those, then regenerate. Replace the two <...> placeholders before use.

package_update: true
package_upgrade: true
packages:
  - openjdk-21-jre-headless
  - sqlite3
  - jq
  - curl
  - ufw
  - unattended-upgrades

users:
  - name: petter
    groups: [sudo]
    shell: /bin/bash
    lock_passwd: true
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "<YOUR PERSONAL SSH PUBLIC KEY>"
  - name: deploy
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - 'command="/opt/flight-tracker/bin/deploy.sh",restrict <GITHUB DEPLOY PUBLIC KEY>'
  - name: flighttracker
    system: true
    shell: /usr/sbin/nologin

write_files:
EOF
file_entry /etc/ssh/sshd_config.d/10-hardening.conf 0644;            indent sshd-hardening.conf
file_entry /etc/sudoers.d/flight-tracker-deploy 0440;                indent sudoers-deploy
file_entry /etc/systemd/system/flight-tracker.service 0644;          indent flight-tracker.service
file_entry /opt/flight-tracker/bin/deploy.sh 0755;                   indent deploy.sh
file_entry /etc/flight-tracker/env 0640 root:flighttracker defer;    indent env.example
cat <<'EOF'
  - path: /etc/apt/apt.conf.d/20auto-upgrades
    permissions: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

runcmd:
  # App directories: bin/ is root-owned so the deploy user can't replace deploy.sh.
  - install -d -o root -g root -m 0755 /opt/flight-tracker /opt/flight-tracker/bin
  - install -d -o deploy -g deploy -m 0755 /opt/flight-tracker/app /opt/flight-tracker/app/releases
  # cloudflared from Cloudflare's apt repo (the tunnel token is added by hand later).
  - install -d -m 0755 /usr/share/keyrings
  - curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg -o /usr/share/keyrings/cloudflare-main.gpg
  - echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' > /etc/apt/sources.list.d/cloudflared.list
  - apt-get update && apt-get install -y cloudflared
  # Host firewall. Port 22 is open only for bootstrap; the guide removes it once
  # SSH through Cloudflare Access works.
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp comment 'bootstrap only, remove after Access SSH works'
  - ufw --force enable
  - systemctl daemon-reload
  - systemctl enable flight-tracker
  - systemctl restart ssh
EOF
} > cloud-init.yaml
echo "wrote $(pwd)/cloud-init.yaml"
